# Usa la imagen base de Python 3.9
FROM python:3.9-slim

# Copiar el archivo requirements.txt
COPY requirements.txt /requirements.txt

# Instalar dependencias de pip
RUN pip install --no-cache-dir -r /requirements.txt
